spring:
  thymeleaf:
    cache: false
  mvc:
    throw-exception-if-no-handler-found: true
  #resources:
  #  add-mappings: false
  h2:
    console:
      enabled: true
      path: /h2-console
  devtools:
    restart:
      enabled: true
  datasource:
    # file base
    # url: jdbc:h2:~/test
    # in-memory
    platform: h2
    url: jdbc:h2:tcp://localhost:9092/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    max-active: 1
    max-idle: 1
    min-idle: 1
    initial-size: 1
    validation-query: select 1
    test-on-borrow: true
    test-on-return: false
    sql-script-encoding: UTF-8
  messages:
    basename: messages
    cache-seconds: -1
    encoding: UTF-8
  error:
     whitelabel:
       enabled: false
server:
  port: 80
  contextPath: /app
  session-timeout: 900
  error:
    path: /globalError
security:
  basic:
    enabled: false
  ignored: /static/**
logging:
  level:
    jp.gr.java_conf.uzresk.springboot.demo: DEBUG
    DumpLogInterceptor: TRACE
    org.springframework.jdbc.core.JdbcTemplate: TRACE
doma:
  dialect: h2